# Generated by Django 2.2.6 on 2019-10-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191001_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='creation_date',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
