# Generated by Django 2.2.6 on 2019-10-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191002_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='creation_date',
        ),
    ]
