# Generated by Django 2.2.6 on 2019-10-02 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
